- Makefile
Set the compiler to C++11 mode as the tests use C++11 features and gcc 5 refuses to compile the code in it's default mode (C++98 mode).
> Compile in C++11 mode

- .travis.yml
- Makefile
- bootstrap.sh
This replaces the use of the Mapnik PPA (https://launchpad.net/~mapnik/+archive/ubuntu/nightly-trunk/+packages) for testing builds. It would be nice to keep testing against the PPA-built Mapnik, however:
- PPA builds are currently broken due to https://github.com/mapnik/mapnik/issues/2677
- PPA builds depend on older apt .deb's for gdal, cairo, etc so this make visual testing a pain (refs https://github.com/mapnik/mapnik/issues/2662)
- PPA builds only happen once a night, which is not fast enough for easy iteration (the mason package will update whenever we push a commit to https://github.com/mapbox/mason/tree/mapnik-dev)
So, Mason-packaged mapnik is a better solution for travis testing. Getting the PPA-based approach working again is not something I am going to put effort into. So …
> Use mason packaged mapnik for travis builds and tests

- src/vector_tile_processor.ipp
- test/vector_tile.cpp
Moves to `boost::geometry::intersection` instead of Clipper: the advantage is that `boost::geometry::intersection` preserves orientation whereas Clipper does not.
BTW, using closed `linear_ring` for the clipping box instead of a true `box` due to this bug: https://github.com/springmeyer/boost-geometry-line-clipping-testcase
> Better line clip

- bench/vtile-transform.cpp
- src/vector_tile_processor.hpp
- src/vector_tile_processor.ipp
- src/vector_tile_strategy.hpp
- test/clipper_test.cpp
- test/vector_tile.cpp
- test/vector_tile_pbf.cpp
In https://github.com/mapbox/mapnik-vector-tile/commit/9dd27291ee7d84507a1b466d3d45a7aa84185791#diff-2aabba777685cca077a1c8766e95e711R39 I optimized the `vector_tile_strategy` significantly to avoid the overhead of the function call to `prj_trans.backward` even when it is a no-op at https://github.com/mapnik/mapnik/blob/b285bde44bb009d5c619d393bb4902cf96bd98d1/src/proj_transform.cpp#L187-L188. I think this was a lot faster because of the excessive amount of non-inlinable function overloads in https://github.com/mapnik/mapnik/blob/b285bde44bb009d5c619d393bb4902cf96bd98d1/include/mapnik/proj_transform.hpp#L47-L58.
This commit optimized further by avoiding the `prj_trans.equal()` call per feature. This speeds up the benchmark noticeably:
```
2249.26ms (cpu 2227.56ms)   | …
```
> Optimize coordinate transformations

- bench/vtile-transform.cpp
- src/vector_tile_processor.hpp
- src/vector_tile_processor.ipp
- src/vector_tile_strategy.hpp
- test/clipper_test.cpp
- test/vector_tile.cpp
This is a change to resolve #134
> Aggressively filter out geometries outside (buffered) tile extents

- examples/c++/Makefile
- examples/c++/tileinfo.cpp
The c++/tileinfo example can't be built. This makes it buildable again.
> Make tileinfo example buildable

- bench/notes.md
- src/vector_tile_datasource.ipp
- src/vector_tile_datasource_pbf.ipp
- src/vector_tile_geometry_decoder.hpp
This optimizes geometry decoding. Currently in `tile_datasource` and `tile_datasource_pbf` we:
1) decode all geometries
2) then call `mapnik::geometry::envelope(geom)`
3) then throw out any geometries that don't intersect with the query box.
This change makes this more efficient:
- each geometry part is thrown out on the fly during decoding
- this allows us to throw out parts of multigeometries that don't occur within the query bbox (potentially speeding up rendering which will need to do less work)
- this also allows us to avoid the overhead of calling `mapnik::geometry::envelope(geom)`. (which I've seen take 5-10% of the time in profiling the `vtile-decode` benchmark)
Profiling shows some overhead to calling `bbox.intersect` per vertex for lines and polygons, so the win is slightly less …
> Filter geometries by bbox during decoding

- .gitmodules
- Makefile
- test/encoding_util.cpp
- test/encoding_util.hpp
- test/geometry_visual_test.cpp
- test/test_main.cpp
- test/vector_tile_projection.cpp
This pull request adds [geometry test data](https://github.com/mapnik/geometry-test-data) to mapnik-vector-tile tests, with the goal of improving coverage and making mapnik-vector-tile robust against various invalid and bad geometries. The current strategy for these tests is:
1. Create many problematic and non-problematic vector files and place them in https://github.com/mapnik/geometry-test-data `input` folder.
2. Run a test that reads the input vector file and performs the clipping and simplification of the vector-tile production process.
3. Compare the resulting clipped-and-simplified tile to a corresponding expected tile in the `expected` folder of geometry-test-data.
refs #153 
cc/ @flippmoke, @springmeyer, @artemp
> Geometry tests

- bench/readme.md
- bench/vtile-encode.cpp
- bench/vtile-transform.cpp
- gyp/build.gyp
Adds executable vector-tile benchmark, `./build/Release/vtile-encode` that takes a geojson datasourceand a `z x y` tile coordinate, and an optional `iterations` parameter. Currently, the test renders the geometry from the geojson onto a vector tile for `iterations` number of times, logging the amount of time it took.
Things I want to add:
cc/ @flippmoke @mapsam @springmeyer
> [WIP] Add vector-tile encoding benchmark

- src/vector_tile_geometry_feature.hpp
- test/unit/encoding/geometry_to_feature_pbf.cpp
Prevent the segfaults that occur when invalid geometries are passed to the layer encoder by rolling back any written geometries, rather than rolling back the entire layer writer.
Note, with this fix, the keys and values added by the invalid feature will stay in the layer, which I think is acceptable for the edge case situation.
cc/ @springmeyer @flippmoke
> Handle invalid geometries in layer encoding

- proto/vector_tile.proto
This allows the .proto to be used with libprotobuf >= 3.x without warnings.
> Mark the .proto as proto2 syntax

- test/data/layer_scale_denom_style.xml
- test/unit/processor/scale_denom_filter.cpp
The test covers filtering layers by scale denominator and shows it works. In https://github.com/mapbox/mapnik-vector-tile/issues/230 is claimed otherwise.
> add test - filtering by scale denominator on layer level

- examples/c++/tileinfo.cpp
> A feature MAY contain an id field. If a feature has an id field, the value of the id SHOULD be unique among the features of the parent layer.
From https://github.com/mapbox/vector-tile-spec/tree/master/2.1#42-features.
Currently tileinfo outputs `0` for unset feature id properties. Instead I think we should have the output make clear that the feature id is unset, which this PR does.
/cc @mapsam
> Tileinfo: disable feature id as unset, when it is

- .travis.yml
- Makefile
- README.md
- bootstrap.sh
- gyp/build.gyp
- install_mason.sh
- scripts/build.sh
#227 ported the build system to use mason. With this PR, mason is still the default if you run `make`. But also you can now build against an external mapnik with `make release_base`
> add back ability to build against external mapnik - refs #227

- src/vector_tile_layer.hpp
- src/vector_tile_processor.hpp
- src/vector_tile_processor.ipp
- test/system/processor_and_datasource.cpp
- test/unit/layer_impl/layer.cpp
- test/unit/processor/variables.cpp
This fixes #218 along with a minor change in node-mapnik
What this does:
- it optionally adds a new member `mapnik::attributes vars` to the mvt processor.
- it is passed by `processor::update_tile` to the `tile_layer`, so that it can set the variables of its associated query from there (empty if not passed to the processor constructor).
(thanks @Algunenano for the advice on the constructor)
This is the [patch](https://github.com/CartoDB/node-mapnik/pull/5/commits/5182b7168f3c460cf19b94d98e9cfb9f9a4512f2) that would be required in node-mapnik to indeed pass the variables to the datasources. I haven't created a PR yet because it makes little sense until this one approved.
> Pass variables to replace tokens in query

- src/vector_tile_composite.hpp
- src/vector_tile_load_tile.hpp
I was considering `ipp` files but decided to use `inline` as it's also being used here and has smaller diff. 
Please  let me know if `ipp` file is preferable.
> add inline attribute to functions implemented in header file

- src/vector_tile_projection.hpp
- src/vector_tile_projection.ipp
I was wondering why on Earth I need tile resolution to compute spherical Mercator tile bounding box in [node-mapnik](https://github.com/mapycz/node-mapnik/blob/13005d429883cb3372db5b9bd56470c1c5ac174a/src/mapnik_vector_tile.cpp#L5146). It is not needed.
> Spherical Mercator tile bounding box is resolution-invariant

- src/vector_tile_projection.hpp
- src/vector_tile_projection.ipp
Reverts mapbox/mapnik-vector-tile#259
I am seeing some different results in tests after this change in node-mapnik. For now I am reverting this change and we can look at pulling back in again. 
/cc @talaj
> Revert "Spherical Mercator tile bounding box is resolution-invariant"

- .travis.yml
- Makefile
- README.md
- gyp/build.gyp
- gyp/common.gypi
- src/vector_tile_douglas_peucker.hpp
- src/vector_tile_geometry_simplifier.hpp
This is similar to #209 but cleaned up. It now wraps the SSE code in a define and fixes some bugs associated with the previous implementation. It has both SSE code for doubles and for floats, based on the size of the container being used. 
The previous bugs in #209 were causing slightly different test results, but the test results are the same with this implementation. 
This code only changes the performance of the simplification code currently.
v3.0.x previous:
```
./build/Release/vtile-encode ./test/geometry-test-data/benchmark/ginormous-polygon.json 0 0 0 -i 100 -p 4326
z:0 x:0 y:0 iterations:100
5435.11ms (cpu 5419.27ms)   | encode tile: ./test/geometry-test-data/benchmark/ginormous-polygon.json
```
sse_revised branch:
```
./build/Release/vtile-encode …
```
> Enable SIMD Instructions for v3.0.x branch

- CHANGELOG.md
- package.json
- src/vector_tile_geometry_clipper.hpp
Fix mistake where initializing 5 values to default values was used rather then reserve in the clipping bound box function. This was causing a strange polygon with 5 extra points at 0,0 to be passed directly into the clipping function. The first I have noticed that caused this was https://github.com/mapnik/node-mapnik/issues/892. We need to patch this and push upstream quickly.
> Fix improper clipping

- CHANGELOG.md
- package.json
- src/vector_tile_layer.hpp
Closes https://github.com/mapbox/mapnik-vector-tile/issues/289
- Changes how the resolution of the mapnik::query is calculated. Given the formula: `X / width` and `X / height`:
- `!ds`: X used to be 256. Now it's 4096.
- `ds.type == datasource::Vector` && `vector_layer_extent` declared: X used to be 256. Now it's equal to `vector_layer_extent`.
- `ds.type == datasource::Vector` && `vector_layer_extent` NOT declared: X used to be 256. Now it's 4096.
` ds.type != datasource::Vector` && `vector_layer_extent` declared. Used to be 256. Stays the same.
` ds.type != datasource::Vector` && `vector_layer_extent` NOT declared. Used to be 4096. Stays the same.
> Layer: Always calculate precision as extent per width|height
