Makefile
Reverts mapbox/mapnik-vector-tile#79
=> Revert "Compile in C++11 mode"

src/vector_tile_processor.hpp, test/encoding_util.hpp, test/geometry_encoding.cpp, test/vector_tile.cpp
Adapts to https://github.com/mapnik/mapnik/pull/2688
=> Use mapnik::vertext_adapter

src/vector_tile_datasource_pbf.ipp, test/data/linestrings_and_point.geojson, test/vector_tile_pbf.cpp
=> Fix indexing error in tile_datasource_pbf

Makefile, gyp/build.gyp, src/vector_tile_datasource_pbf.hpp, src/vector_tile_datasource_pbf.ipp, src/vector_tile_geometry_decoder.hpp, src/vector_tile_geometry_encoder.hpp, test/vector_tile.cpp, test/vector_tile_pbf.cpp
- refs https://github.com/mapbox/protozero/releases/tag/v1.0.0
=> Upgrade to protozero 1.0.0

src/vector_tile_util.hpp, src/vector_tile_util.ipp, test/vector_tile.cpp, test/vector_tile_pbf.cpp
refs https://github.com/mapnik/node-mapnik/issues/422
=> is_solid impl that works on raw bytes

examples/c++/Makefile, examples/c++/tileinfo.cpp
Reverts mapbox/mapnik-vector-tile#142
=> Revert "Make tileinfo example buildable"

src/vector_tile_backend_pbf.hpp, src/vector_tile_geometry_encoder.hpp, src/vector_tile_processor.hpp, src/vector_tile_processor.ipp
=> Updated the way that painted is determined within vector tiles

bench/vtile-decode.cpp, src/vector_tile_datasource_pbf.ipp, src/vector_tile_geometry_encoder.hpp, src/vector_tile_util.ipp, test/vector_tile_pbf.cpp
This pull request contains several protozero-related changes.
=> Several protozero-related changes

src/vector_tile_processor.hpp, src/vector_tile_processor.ipp, test/geometry_visual_test.cpp, test/vector_tile.cpp
Allow users of the library to pick the type of polygon fill operation used.
/cc @springmeyer
=> Exposed fill order for polygons

src/vector_tile_processor.hpp, src/vector_tile_processor.ipp, test/vector_tile.cpp
=> Added the ability for multipolygons to be unioned

bench/vtile-geometry-encode.cpp, gyp/build.gyp, src/vector_tile_geometry_encoder.hpp
Adds benchmark for encoding geometries into `Tile_Feature`s.
cc/ @flippmoke
=> [WIP] Geometry encoding benchmark

package.json
=> bump to v1.0.0 for v2 push

src/vector_tile_layer.hpp
=> use source layer projection for query resolution

.travis.yml, codecov.yml, scripts/coverage.sh
Moves us to codecov, refs #236
=> Repair code coverage checking and reporting

.travis.yml
Avoids hitting https://github.com/mapbox/mason/issues/389
=> Upgrade to latest Xcode

src/vector_tile_geometry_decoder.ipp, test/unit/decoding/linestring.cpp, test/unit/decoding/point.cpp, test/unit/decoding/polygon.cpp
Patch to this for the v3.0.x development branch
=> Limit Reserve Size v3.0.x

src/vector_tile_geometry_decoder.ipp, test/unit/decoding/linestring.cpp, test/unit/decoding/point.cpp, test/unit/decoding/polygon.cpp
Put limits on the allocation sizes of geometry
=> Limit Reserve Size 

.travis.yml, Makefile, README.md, gyp/build.gyp, src/vector_tile_douglas_peucker.hpp, src/vector_tile_geometry_simplifier.hpp
Added SSE execution for simplification to improve performance, same as #268 but on master branch.
=> Enable SIMD Instructions for Simplification

src/vector_tile_tile.hpp, src/vector_tile_tile.ipp, test/unit/tile_impl/tile.cpp
Added ability for tile buffer to be released by changing it to be a unique_ptr
=> Change Tile Buffer to be Unique Ptr

Makefile
This hopefully will resolve #292.
=> Change to another version of gyp that is maintained
